##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /site
# location of code, the full url to your github repository
source-code: https://gnmedatabase.github.io/site/

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Middle East and North Africa Illustrated
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A Bibliographic Database of Graphic Novels in English
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Middle East and North Africa Illustrated (MENAI) is an annually updated database of bibliographical information on all graphic novels that are related to the Western Asian and North African countries.  It includes a variety of representations of the Middle East and North Africa in the graphic novel format and various genres that are written in or translated into English. The database is formed in relation to the HONORS 212 Near/Middle East Illustrated course that was offered by Selim S. Kuru for the first time in the 2020 Spring Quarter for the HONORS Program at the University of Washington. The database received support from the Department of Middle Eastern Languages and Cultures and the HONORS Program at the University of Washington.
<br>MENAI appreciates any feedback or corrections. If you’ve read a graphic novel or any sort of sequential creative work in visual language about MENA region that’s not yet in the database, let us know through gnmedatabase@gmail.com.<br/>
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: GNME

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: gnme 

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
